<?php

$dictionary['Note']['fields']['label_c'] = array(
    'inline_edit' => '1',
    'labelValue' => 'Label',
    'required' => false,
    'name' => 'label_c',
    'vname' => 'LBL_LABEL_C',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => '',
    'studio' => 'visible',
    'dependency' => false,
);